spring:
  mail:
    properties:
      mail:
        smtp:
          starttls:
            enable: 'true'
          timeout: '5000'
          auth: 'true'
          connectiontimeout: '5000'
          writetimeout: '5000'
    host: smtp.gmail.com
    username: mhuseinov7@gmail.com
    password: tlvamdpoilqxvcmy
    port: '587'